development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  #url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>#
  url: <%= ENV['DATABASE_URL'] %>
  channel_prefix: southern-creations_production
